# Generated by Django 5.0.7 on 2024-12-09 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimatesGameAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstances',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
