# Generated by Django 5.0.7 on 2024-07-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimatesGameAPI', '0002_alter_fixationgameconfig_instance_fixationgamereport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixationgameresult',
            name='buttonsize',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
