# Generated by Django 5.0.7 on 2024-12-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimatesGameAPI', '0002_gameinstances_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixationgameconfig',
            name='botton_holdDuration',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
