# Generated by Django 5.0.7 on 2024-09-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimatesGameAPI', '0003_fixationgameresult_buttonsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixationgamereport',
            name='gamereportname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
