# Generated by Django 5.0.7 on 2024-12-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimatesGameAPI', '0003_fixationgameconfig_botton_holdduration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixationgameconfig',
            old_name='botton_holdDuration',
            new_name='button_holdDuration',
        ),
    ]
