# Generated by Django 5.0.7 on 2024-09-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimatesGameAPI', '0004_fixationgamereport_gamereportname'),
    ]

    operations = [
        migrations.AddField(
            model_name='primates',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
