# Generated by Django 5.0.7 on 2025-03-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimatesGameAPI', '0004_rename_botton_holdduration_fixationgameconfig_button_holdduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='primates',
            name='rfid_tag',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
