# Generated by Django 5.0.7 on 2025-03-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimatesGameAPI', '0005_primates_rfid_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primates',
            name='rfid_tag',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
