# Generated by Django 5.0.7 on 2024-11-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimatesGameAPI', '0005_primates_is_occupied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpistates',
            old_name='gp17',
            new_name='motor',
        ),
    ]
