# Generated by Django 5.0.7 on 2025-03-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimatesGameAPI', '0006_alter_primates_rfid_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixationgameconfig',
            name='button_holdDuration',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='fixationgameconfig',
            name='interval_absent',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='fixationgameconfig',
            name='interval_correct',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='fixationgameconfig',
            name='interval_incorrect',
            field=models.IntegerField(default=5),
        ),
    ]
