# Generated by Django 5.0.7 on 2025-04-01 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimatesGameAPI', '0007_alter_fixationgameconfig_button_holdduration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primates',
            name='game_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PrimatesGameAPI.gameinstances'),
        ),
    ]
