# Generated by Django 5.0.7 on 2025-04-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimatesGameAPI', '0008_primates_game_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpiboards',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
